import dotenv from "dotenv";
dotenv.config();

import prisma from "../config/prisma.js";

const defaultContactPageData = {
  page: "contact-us",
  hero: {
    breadcrumb: "CONTACT US",
    title: {
      value: "Every meaningful journey begins with a conversation.",
      textColor: "#ffffff",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    subtitle: {
      value: "",
      textColor: "#E5E7EB",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    description: {
      value: "We design thoughtful journeys shaped around your pace, interests, and sense of discovery.",
      textColor: "#F3F4F6",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    isCenter: false,
    buttons: [
      {
        label: "Plan your escape",
        url: "#contact-form-section",
        variant: "PRIMARY",
        style: "primary",
        rounded: "full",
        backgroundColor: "#182D09",
        backgroundOpacity: 100,
        textColor: "#ffffff",
        textOpacity: 100,
        target: "_self",
        showIcon: true,
      },
    ],
    backgroundMultimedia: {
      show: "video",
      color: {
        color: "#FAF7F2",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "",
        alt: "Contact Hero Background",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "https://res.cloudinary.com/dscqp4wwt/video/upload/v1789788545/P/heroVideo/rxtfn6pkii7whiix2knj.mp4",
        alt: null,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        autoplay: true,
        loop: true,
        muted: true,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
  },
  process: {
    title: {
      value: "How The Process Works",
      textColor: "#182D09",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    items: [
      {
        badge: "STEP 01",
        title: {
          value: "Share your travel ideas",
          textColor: "#182D09",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
        description: {
          value: "Tell us about your dreams, preferred pace, and the experiences that move you.",
          textColor: "#4B5563",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
      },
      {
        badge: "STEP 02",
        title: {
          value: "We curate your journey",
          textColor: "#182D09",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
        description: {
          value: "Our specialists draft a narrative itinerary that balances discovery with moments of rest.",
          textColor: "#4B5563",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
      },
      {
        badge: "STEP 03",
        title: {
          value: "Refine every detail together",
          textColor: "#182D09",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
        description: {
          value: "We iterate until the itinerary feels perfect, ensuring every stay and connection is seamless.",
          textColor: "#4B5563",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
      },
    ],
    backgroundMultimedia: {
      show: "color",
      color: {
        color: "#FFFFFF",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "",
        alt: "Process Background Image",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: null,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        autoplay: true,
        loop: true,
        muted: true,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
  },
  inquiry_form: {
    eyebrow: {
      value: "THE INQUIRY",
      textColor: "#9A3412",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    title: {
      value: "Plan your escape",
      textColor: "#182D09",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    rightSideMultimedia: {
      show: "image",
      color: {
        color: "#E5E7EB",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "https://res.cloudinary.com/dscqp4wwt/image/upload/v1789788548/P/inquiryImage/bft1icuem9c4tgloaiyz.png",
        alt: "Plan your escape",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: null,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        autoplay: true,
        loop: true,
        muted: true,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
    backgroundMultimedia: {
      show: "color",
      color: {
        color: "#FAF7F2",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "",
        alt: "Inquiry Background",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: null,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        autoplay: true,
        loop: true,
        muted: true,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
  },
  plan_travel: {
    label: {
      value: "A PERSONAL APPROACH",
      textColor: "#B86B3A",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    title: {
      value: "A more thoughtful way to plan travel.",
      textColor: "#182D09",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    description: {
      value: "We believe every traveler moves differently.\n\nThat is why every journey begins with conversation, not templates.\n\nOur team works closely with each traveler to design experiences that feel balanced, personal, and deeply connected to the region.",
      textColor: "#4B5563",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    leftSideMultimedia: {
      show: "image",
      color: {
        color: "#E5E7EB",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "https://res.cloudinary.com/dscqp4wwt/image/upload/v1789788549/P/planTravelImage/admauri5bfob1kekg3bf.png",
        alt: "A Personal Approach",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: null,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        autoplay: true,
        loop: true,
        muted: true,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
    backgroundMultimedia: {
      show: "color",
      color: {
        color: "#F5F3EF",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "",
        alt: "Plan Travel Background",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: null,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        autoplay: true,
        loop: true,
        muted: true,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
  },
  contact_info: {
    items: [
      {
        label: {
          value: "EMAIL",
          textColor: "#6B7280",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
        subtitle: {
          value: "hello@miratravel.com",
          textColor: "#182D09",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
        button: {
          label: "Email Us",
          url: "mailto:hello@miratravel.com",
          variant: "PRIMARY",
          style: "primary",
          rounded: "none",
          backgroundColor: "#182D09",
          backgroundOpacity: 100,
          textColor: "#ffffff",
          textOpacity: 100,
          hoverBackgroundColor: "#f3f4f6",
          hoverTextColor: "#000000",
          target: "_self",
          showIcon: true,
        },
        multimedia: {
          show: "image",
          color: {
            color: "#E5E7EB",
            opacity: 100,
            width: "100%",
            height: "100%",
            aspectRatio: "auto",
          },
          image: {
            url: "",
            alt: "Email icon",
            opacity: 100,
            overlayColor: "#000000",
            overlayOpacity: 0,
            width: "100%",
            height: "auto",
            aspectRatio: "auto",
            fit: "cover",
          },
          video: {
            url: "",
            alt: "Email icon",
            opacity: 100,
            overlayColor: "#000000",
            overlayOpacity: 0,
            autoplay: true,
            loop: true,
            muted: true,
            width: "100%",
            height: "auto",
            aspectRatio: "auto",
            fit: "cover",
          },
        },
      },
      {
        label: {
          value: "WHATSAPP",
          textColor: "#6B7280",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
        subtitle: {
          value: "+355 69 123 4567",
          textColor: "#182D09",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
        button: {
          label: "Chat on WhatsApp",
          url: "https://wa.me/355691234567",
          variant: "PRIMARY",
          style: "primary",
          rounded: "none",
          backgroundColor: "#182D09",
          backgroundOpacity: 100,
          textColor: "#ffffff",
          textOpacity: 100,
          hoverBackgroundColor: "#f3f4f6",
          hoverTextColor: "#000000",
          target: "_blank",
          showIcon: true,
        },
        multimedia: {
          show: "image",
          color: {
            color: "#E5E7EB",
            opacity: 100,
            width: "100%",
            height: "100%",
            aspectRatio: "auto",
          },
          image: {
            url: "",
            alt: "WhatsApp icon",
            opacity: 100,
            overlayColor: "#000000",
            overlayOpacity: 0,
            width: "100%",
            height: "auto",
            aspectRatio: "auto",
            fit: "cover",
          },
          video: {
            url: "",
            alt: "WhatsApp icon",
            opacity: 100,
            overlayColor: "#000000",
            overlayOpacity: 0,
            autoplay: true,
            loop: true,
            muted: true,
            width: "100%",
            height: "auto",
            aspectRatio: "auto",
            fit: "cover",
          },
        },
      },
      {
        label: {
          value: "RESPONSE TIME",
          textColor: "#6B7280",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
        subtitle: {
          value: "We typically respond within 24 hours.",
          textColor: "#182D09",
          textOpacity: 1,
          backgroundColor: null,
          backgroundOpacity: 1,
        },
        button: {
          label: "",
          url: "",
          variant: "PRIMARY",
          style: "primary",
          rounded: "none",
          backgroundColor: "#182D09",
          backgroundOpacity: 100,
          textColor: "#ffffff",
          textOpacity: 100,
          hoverBackgroundColor: "#f3f4f6",
          hoverTextColor: "#000000",
          target: "_self",
          showIcon: true,
        },
        multimedia: {
          show: "image",
          color: {
            color: "#E5E7EB",
            opacity: 100,
            width: "100%",
            height: "100%",
            aspectRatio: "auto",
          },
          image: {
            url: "",
            alt: "Response time icon",
            opacity: 100,
            overlayColor: "#000000",
            overlayOpacity: 0,
            width: "100%",
            height: "auto",
            aspectRatio: "auto",
            fit: "cover",
          },
          video: {
            url: "",
            alt: "Response time icon",
            opacity: 100,
            overlayColor: "#000000",
            overlayOpacity: 0,
            autoplay: true,
            loop: true,
            muted: true,
            width: "100%",
            height: "auto",
            aspectRatio: "auto",
            fit: "cover",
          },
        },
      },
    ],
    backgroundMultimedia: {
      show: "color",
      color: {
        color: "#FFFFFF",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "",
        alt: "Contact info section background image",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 45,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: "Contact info section background video",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 45,
        autoplay: true,
        loop: true,
        muted: true,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
  },
  cta: {
    title: {
      value: "Let Us Curate Your Experience",
      textColor: "#182D09",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    description: {
      value: "Let us help you plan a journey filled with unforgettable experiences and meaningful moments",
      textColor: "#4B5563",
      textOpacity: 1,
      backgroundColor: null,
      backgroundOpacity: 1,
    },
    backgroundMultimedia: {
      show: "color",
      color: {
        color: "#FBF9F5",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "",
        alt: null,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: null,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        autoplay: true,
        loop: true,
        muted: true,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
    rightSideMultimedia: {
      show: "image",
      color: {
        color: "#FBF9F5",
        opacity: 100,
        width: "100%",
        height: "100%",
        aspectRatio: "auto",
      },
      image: {
        url: "",
        alt: "Let us design your journey",
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
      video: {
        url: "",
        alt: null,
        opacity: 100,
        overlayColor: "#000000",
        overlayOpacity: 0,
        autoplay: true,
        loop: true,
        muted: true,
        width: "100%",
        height: "auto",
        aspectRatio: "auto",
        fit: "cover",
      },
    },
    buttons: [
      {
        label: "Start Your Journey",
        url: "#contact-form-section",
        variant: "PRIMARY",
        style: "primary",
        rounded: "full",
        backgroundColor: "#182D09",
        backgroundOpacity: 100,
        textColor: "#ffffff",
        textOpacity: 100,
        hoverBackgroundColor: "#f3f4f6",
        hoverTextColor: "#000000",
        target: "_self",
        showIcon: true,
      },
    ],
  },
  seo: {
    title: "Contact Us | MIRA Travel",
    description: "Contact MIRA Travel luxury designers to plan your personal journey across the Balkans.",
    keywords: ["Contact", "Luxury Travel", "Balkans", "Bespoke Journeys", "MIRA Travel"],
    canonicalUrl: "https://miratravel.nl/contact-us",
    robots: {
      index: true,
      follow: true,
    },
  },
};

async function seedContactCmsPage() {
  console.log("Seeding / updating 'contact-us' CMS Page in Neon PostgreSQL DB...");

  const existing = await prisma.cmsPage.findFirst({
    where: { slug: "contact-us" },
  });

  if (existing) {
    const updated = await prisma.cmsPage.update({
      where: { id: existing.id },
      data: {
        name: "Contact Us",
        slug: "contact-us",
        metadata: {
          title: "Contact Us | MIRA Travel",
          description: "Contact MIRA Travel luxury designers to plan your personal journey across the Balkans.",
        },
        data: defaultContactPageData,
      },
    });
    console.log("Successfully updated 'contact-us' CMS Page in DB. ID:", updated.id);
  } else {
    const created = await prisma.cmsPage.create({
      data: {
        name: "Contact Us",
        slug: "contact-us",
        metadata: {
          title: "Contact Us | MIRA Travel",
          description: "Contact MIRA Travel luxury designers to plan your personal journey across the Balkans.",
        },
        data: defaultContactPageData,
      },
    });
    console.log("Successfully created 'contact-us' CMS Page in DB. ID:", created.id);
  }
}

seedContactCmsPage()
  .catch((e) => {
    console.error("Seed script failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
